package com.cmpay.boss.entity.vo;

import java.util.Date;
import java.util.List;

public class SYSROLEVO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_SYS_ROLE.ROLE_ID
     *
     * @mbggenerated
     */
    private String          roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_SYS_ROLE.ROLE_NAME
     *
     * @mbggenerated
     */
    private String          roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_SYS_ROLE.ROLE_DISABLE_TAG
     *
     * @mbggenerated
     */
    private String          roleDisableTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_SYS_ROLE.ROLE_REMARK
     *
     * @mbggenerated
     */
    private String          roleRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_SYS_ROLE.ROLE_CREATE_BY
     *
     * @mbggenerated
     */
    private String          roleCreateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_SYS_ROLE.ROLE_CREATE_DATETIME
     *
     * @mbggenerated
     */
    private Date            roleCreateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_SYS_ROLE.ROLE_UPDATETIME_BY
     *
     * @mbggenerated
     */
    private String          roleUpdatetimeBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_SYS_ROLE.ROLE_UPDATETIME_DATETIME
     *
     * @mbggenerated
     */
    private Date            roleUpdatetimeDatetime;

    private List<SYSFUNCVO> _SYSFUNCVOList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_SYS_ROLE.ROLE_ID
     *
     * @return the value of TBL_BTS_SYS_ROLE.ROLE_ID
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_SYS_ROLE.ROLE_ID
     *
     * @param roleId the value for TBL_BTS_SYS_ROLE.ROLE_ID
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_SYS_ROLE.ROLE_NAME
     *
     * @return the value of TBL_BTS_SYS_ROLE.ROLE_NAME
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_SYS_ROLE.ROLE_NAME
     *
     * @param roleName the value for TBL_BTS_SYS_ROLE.ROLE_NAME
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_SYS_ROLE.ROLE_DISABLE_TAG
     *
     * @return the value of TBL_BTS_SYS_ROLE.ROLE_DISABLE_TAG
     *
     * @mbggenerated
     */
    public String getRoleDisableTag() {
        return roleDisableTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_SYS_ROLE.ROLE_DISABLE_TAG
     *
     * @param roleDisableTag the value for TBL_BTS_SYS_ROLE.ROLE_DISABLE_TAG
     *
     * @mbggenerated
     */
    public void setRoleDisableTag(String roleDisableTag) {
        this.roleDisableTag = roleDisableTag == null ? null : roleDisableTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_SYS_ROLE.ROLE_REMARK
     *
     * @return the value of TBL_BTS_SYS_ROLE.ROLE_REMARK
     *
     * @mbggenerated
     */
    public String getRoleRemark() {
        return roleRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_SYS_ROLE.ROLE_REMARK
     *
     * @param roleRemark the value for TBL_BTS_SYS_ROLE.ROLE_REMARK
     *
     * @mbggenerated
     */
    public void setRoleRemark(String roleRemark) {
        this.roleRemark = roleRemark == null ? null : roleRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_SYS_ROLE.ROLE_CREATE_BY
     *
     * @return the value of TBL_BTS_SYS_ROLE.ROLE_CREATE_BY
     *
     * @mbggenerated
     */
    public String getRoleCreateBy() {
        return roleCreateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_SYS_ROLE.ROLE_CREATE_BY
     *
     * @param roleCreateBy the value for TBL_BTS_SYS_ROLE.ROLE_CREATE_BY
     *
     * @mbggenerated
     */
    public void setRoleCreateBy(String roleCreateBy) {
        this.roleCreateBy = roleCreateBy == null ? null : roleCreateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_SYS_ROLE.ROLE_CREATE_DATETIME
     *
     * @return the value of TBL_BTS_SYS_ROLE.ROLE_CREATE_DATETIME
     *
     * @mbggenerated
     */
    public Date getRoleCreateDatetime() {
        return roleCreateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_SYS_ROLE.ROLE_CREATE_DATETIME
     *
     * @param roleCreateDatetime the value for TBL_BTS_SYS_ROLE.ROLE_CREATE_DATETIME
     *
     * @mbggenerated
     */
    public void setRoleCreateDatetime(Date roleCreateDatetime) {
        this.roleCreateDatetime = roleCreateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_SYS_ROLE.ROLE_UPDATETIME_BY
     *
     * @return the value of TBL_BTS_SYS_ROLE.ROLE_UPDATETIME_BY
     *
     * @mbggenerated
     */
    public String getRoleUpdatetimeBy() {
        return roleUpdatetimeBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_SYS_ROLE.ROLE_UPDATETIME_BY
     *
     * @param roleUpdatetimeBy the value for TBL_BTS_SYS_ROLE.ROLE_UPDATETIME_BY
     *
     * @mbggenerated
     */
    public void setRoleUpdatetimeBy(String roleUpdatetimeBy) {
        this.roleUpdatetimeBy = roleUpdatetimeBy == null ? null : roleUpdatetimeBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_SYS_ROLE.ROLE_UPDATETIME_DATETIME
     *
     * @return the value of TBL_BTS_SYS_ROLE.ROLE_UPDATETIME_DATETIME
     *
     * @mbggenerated
     */
    public Date getRoleUpdatetimeDatetime() {
        return roleUpdatetimeDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_SYS_ROLE.ROLE_UPDATETIME_DATETIME
     *
     * @param roleUpdatetimeDatetime the value for TBL_BTS_SYS_ROLE.ROLE_UPDATETIME_DATETIME
     *
     * @mbggenerated
     */
    public void setRoleUpdatetimeDatetime(Date roleUpdatetimeDatetime) {
        this.roleUpdatetimeDatetime = roleUpdatetimeDatetime;
    }

    public List<SYSFUNCVO> getSYSFUNCVOList() {
        return _SYSFUNCVOList;
    }

    public void setSYSFUNCVOList(List<SYSFUNCVO> _SYSFUNCVOList) {
        this._SYSFUNCVOList = _SYSFUNCVOList;
    }
}