package com.cmpay.boss.entity.vo;

import java.util.Date;
import java.util.List;

public class SYSUSRVO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_SYS_USR.USR_ID
     *
     * @mbggenerated
     */
    private String          usrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_SYS_USR.USR_NAME
     *
     * @mbggenerated
     */
    private String          usrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_SYS_USR.USR_PWD
     *
     * @mbggenerated
     */
    private String          usrPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_SYS_USR.USR_REMARK
     *
     * @mbggenerated
     */
    private String          usrRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_SYS_USR.USR_DISABLE_TAG
     *
     * @mbggenerated
     */
    private String          usrDisableTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_SYS_USR.USR_EMAIL
     *
     * @mbggenerated
     */
    private String          usrEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_SYS_USR.USR_CREATE_BY
     *
     * @mbggenerated
     */
    private String          usrCreateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_SYS_USR.USR_CREATE_DATE
     *
     * @mbggenerated
     */
    private Date            usrCreateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_SYS_USR.USR_UPDATE_BY
     *
     * @mbggenerated
     */
    private String          usrUpdateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_SYS_USR.USR_UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date            usrUpdateDate;

    private List<SYSROLEVO> _SYSROLEVOLIST;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_SYS_USR.USR_ID
     *
     * @return the value of TBL_BTS_SYS_USR.USR_ID
     *
     * @mbggenerated
     */
    public String getUsrId() {
        return usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_SYS_USR.USR_ID
     *
     * @param usrId the value for TBL_BTS_SYS_USR.USR_ID
     *
     * @mbggenerated
     */
    public void setUsrId(String usrId) {
        this.usrId = usrId == null ? null : usrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_SYS_USR.USR_NAME
     *
     * @return the value of TBL_BTS_SYS_USR.USR_NAME
     *
     * @mbggenerated
     */
    public String getUsrName() {
        return usrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_SYS_USR.USR_NAME
     *
     * @param usrName the value for TBL_BTS_SYS_USR.USR_NAME
     *
     * @mbggenerated
     */
    public void setUsrName(String usrName) {
        this.usrName = usrName == null ? null : usrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_SYS_USR.USR_PWD
     *
     * @return the value of TBL_BTS_SYS_USR.USR_PWD
     *
     * @mbggenerated
     */
    public String getUsrPwd() {
        return usrPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_SYS_USR.USR_PWD
     *
     * @param usrPwd the value for TBL_BTS_SYS_USR.USR_PWD
     *
     * @mbggenerated
     */
    public void setUsrPwd(String usrPwd) {
        this.usrPwd = usrPwd == null ? null : usrPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_SYS_USR.USR_REMARK
     *
     * @return the value of TBL_BTS_SYS_USR.USR_REMARK
     *
     * @mbggenerated
     */
    public String getUsrRemark() {
        return usrRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_SYS_USR.USR_REMARK
     *
     * @param usrRemark the value for TBL_BTS_SYS_USR.USR_REMARK
     *
     * @mbggenerated
     */
    public void setUsrRemark(String usrRemark) {
        this.usrRemark = usrRemark == null ? null : usrRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_SYS_USR.USR_DISABLE_TAG
     *
     * @return the value of TBL_BTS_SYS_USR.USR_DISABLE_TAG
     *
     * @mbggenerated
     */
    public String getUsrDisableTag() {
        return usrDisableTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_SYS_USR.USR_DISABLE_TAG
     *
     * @param usrDisableTag the value for TBL_BTS_SYS_USR.USR_DISABLE_TAG
     *
     * @mbggenerated
     */
    public void setUsrDisableTag(String usrDisableTag) {
        this.usrDisableTag = usrDisableTag == null ? null : usrDisableTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_SYS_USR.USR_EMAIL
     *
     * @return the value of TBL_BTS_SYS_USR.USR_EMAIL
     *
     * @mbggenerated
     */
    public String getUsrEmail() {
        return usrEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_SYS_USR.USR_EMAIL
     *
     * @param usrEmail the value for TBL_BTS_SYS_USR.USR_EMAIL
     *
     * @mbggenerated
     */
    public void setUsrEmail(String usrEmail) {
        this.usrEmail = usrEmail == null ? null : usrEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_SYS_USR.USR_CREATE_BY
     *
     * @return the value of TBL_BTS_SYS_USR.USR_CREATE_BY
     *
     * @mbggenerated
     */
    public String getUsrCreateBy() {
        return usrCreateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_SYS_USR.USR_CREATE_BY
     *
     * @param usrCreateBy the value for TBL_BTS_SYS_USR.USR_CREATE_BY
     *
     * @mbggenerated
     */
    public void setUsrCreateBy(String usrCreateBy) {
        this.usrCreateBy = usrCreateBy == null ? null : usrCreateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_SYS_USR.USR_CREATE_DATE
     *
     * @return the value of TBL_BTS_SYS_USR.USR_CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getUsrCreateDate() {
        return usrCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_SYS_USR.USR_CREATE_DATE
     *
     * @param usrCreateDate the value for TBL_BTS_SYS_USR.USR_CREATE_DATE
     *
     * @mbggenerated
     */
    public void setUsrCreateDate(Date usrCreateDate) {
        this.usrCreateDate = usrCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_SYS_USR.USR_UPDATE_BY
     *
     * @return the value of TBL_BTS_SYS_USR.USR_UPDATE_BY
     *
     * @mbggenerated
     */
    public String getUsrUpdateBy() {
        return usrUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_SYS_USR.USR_UPDATE_BY
     *
     * @param usrUpdateBy the value for TBL_BTS_SYS_USR.USR_UPDATE_BY
     *
     * @mbggenerated
     */
    public void setUsrUpdateBy(String usrUpdateBy) {
        this.usrUpdateBy = usrUpdateBy == null ? null : usrUpdateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_SYS_USR.USR_UPDATE_DATE
     *
     * @return the value of TBL_BTS_SYS_USR.USR_UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getUsrUpdateDate() {
        return usrUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_SYS_USR.USR_UPDATE_DATE
     *
     * @param usrUpdateDate the value for TBL_BTS_SYS_USR.USR_UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUsrUpdateDate(Date usrUpdateDate) {
        this.usrUpdateDate = usrUpdateDate;
    }

    public List<SYSROLEVO> getSYSROLEVOList() {
        return _SYSROLEVOLIST;
    }

    public void setSYSROLEVOList(List<SYSROLEVO> _SYSROLEVOLIST) {
        this._SYSROLEVOLIST = _SYSROLEVOLIST;
    }
}